### ISSUE TITLE
Feature #1 See Car

### ISSUE THREAD

**Issue by paulpark330** [paulpark330/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create HTML and CSS layout
- [x] Set position for car
- [x] Set background color
